--------------------------------------------------------
--  File created - четверг-сент€бр€-08-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Index KOD_TOVARA
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER2022"."KOD_TOVARA" ON "USER2022"."EDINICA_TOVARA" ("KOD_TOVARA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007420
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER2022"."SYS_C007420" ON "USER2022"."USERS" ("ID_USER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007422
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER2022"."SYS_C007422" ON "USER2022"."PRODUCT" ("ID_PRODUCT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007427
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER2022"."SYS_C007427" ON "USER2022"."ORDERS" ("ID_ORDER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007432
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER2022"."SYS_C007432" ON "USER2022"."CATEGORIES" ("ID_CATEGORIES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007436
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER2022"."SYS_C007436" ON "USER2022"."STATUS_ORDERS" ("ID_STATUS_ORDERS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007492
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER2022"."SYS_C007492" ON "USER2022"."STORES" ("ID_STORES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007494
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER2022"."SYS_C007494" ON "USER2022"."CITY" ("ID_CITY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007504
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER2022"."SYS_C007504" ON "USER2022"."TYPE_RECEIPT_ORDER" ("ID_TYPE_RECEIPT_ORDER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007548
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER2022"."SYS_C007548" ON "USER2022"."EXEC_ORDERS" ("ID_EXEC_ORDERS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007570
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER2022"."SYS_C007570" ON "USER2022"."STATUS_TOVARA" ("ID_STATUS_TOVARA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007589
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER2022"."SYS_C007589" ON "USER2022"."EDINICA_TOVARA" ("ID_EDINICA_TOVARA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007591
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER2022"."SYS_C007591" ON "USER2022"."ORDERS" ("ID_EDINICA_TOVARA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table EDINICA_TOVARA
--------------------------------------------------------

  ALTER TABLE "USER2022"."EDINICA_TOVARA" MODIFY ("ID_EDINICA_TOVARA" NOT NULL ENABLE);
  ALTER TABLE "USER2022"."EDINICA_TOVARA" MODIFY ("ID_PRODUCT_VER" NOT NULL ENABLE);
  ALTER TABLE "USER2022"."EDINICA_TOVARA" ADD CONSTRAINT "KOD_TOVARA" UNIQUE ("KOD_TOVARA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "USER2022"."EDINICA_TOVARA" MODIFY ("ID_STORES" NOT NULL ENABLE);
  ALTER TABLE "USER2022"."EDINICA_TOVARA" ADD PRIMARY KEY ("ID_EDINICA_TOVARA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STORES
--------------------------------------------------------

  ALTER TABLE "USER2022"."STORES" MODIFY ("ID_STORES" NOT NULL ENABLE);
  ALTER TABLE "USER2022"."STORES" ADD PRIMARY KEY ("ID_STORES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "USER2022"."STORES" MODIFY ("ID_CITY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STATUS_TOVARA
--------------------------------------------------------

  ALTER TABLE "USER2022"."STATUS_TOVARA" MODIFY ("ID_STATUS_TOVARA" NOT NULL ENABLE);
  ALTER TABLE "USER2022"."STATUS_TOVARA" ADD PRIMARY KEY ("ID_STATUS_TOVARA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "USER2022"."PRODUCT" MODIFY ("ID_PRODUCT" NOT NULL ENABLE);
  ALTER TABLE "USER2022"."PRODUCT" ADD PRIMARY KEY ("ID_PRODUCT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CITY
--------------------------------------------------------

  ALTER TABLE "USER2022"."CITY" MODIFY ("ID_CITY" NOT NULL ENABLE);
  ALTER TABLE "USER2022"."CITY" ADD PRIMARY KEY ("ID_CITY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "USER2022"."ORDERS" MODIFY ("ID_ORDER" NOT NULL ENABLE);
  ALTER TABLE "USER2022"."ORDERS" MODIFY ("ID_USER" NOT NULL ENABLE);
  ALTER TABLE "USER2022"."ORDERS" MODIFY ("ID_EDINICA_TOVARA" NOT NULL ENABLE);
  ALTER TABLE "USER2022"."ORDERS" ADD PRIMARY KEY ("ID_ORDER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "USER2022"."ORDERS" ADD UNIQUE ("ID_EDINICA_TOVARA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "USER2022"."ORDERS" MODIFY ("ID_STATUS_ORDERS" NOT NULL ENABLE);
  ALTER TABLE "USER2022"."ORDERS" MODIFY ("ID_STORES" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CATEGORIES
--------------------------------------------------------

  ALTER TABLE "USER2022"."CATEGORIES" MODIFY ("ID_CATEGORIES" NOT NULL ENABLE);
  ALTER TABLE "USER2022"."CATEGORIES" ADD PRIMARY KEY ("ID_CATEGORIES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EXEC_ORDERS
--------------------------------------------------------

  ALTER TABLE "USER2022"."EXEC_ORDERS" MODIFY ("ID_ORDERS" NOT NULL ENABLE);
  ALTER TABLE "USER2022"."EXEC_ORDERS" MODIFY ("ID_EXEC_ORDERS" NOT NULL ENABLE);
  ALTER TABLE "USER2022"."EXEC_ORDERS" ADD PRIMARY KEY ("ID_EXEC_ORDERS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "USER2022"."EXEC_ORDERS" MODIFY ("ID_TYPE_RECEIPT_ORDER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCT_CATEGORIES
--------------------------------------------------------

  ALTER TABLE "USER2022"."PRODUCT_CATEGORIES" MODIFY ("ID_PRODUCT_VER" NOT NULL ENABLE);
  ALTER TABLE "USER2022"."PRODUCT_CATEGORIES" MODIFY ("ID_CATEGORIES" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "USER2022"."USERS" MODIFY ("ID_USER" NOT NULL ENABLE);
  ALTER TABLE "USER2022"."USERS" ADD PRIMARY KEY ("ID_USER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "USER2022"."USERS" MODIFY ("NAME_USER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STATUS_ORDERS
--------------------------------------------------------

  ALTER TABLE "USER2022"."STATUS_ORDERS" MODIFY ("ID_STATUS_ORDERS" NOT NULL ENABLE);
  ALTER TABLE "USER2022"."STATUS_ORDERS" ADD PRIMARY KEY ("ID_STATUS_ORDERS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TYPE_RECEIPT_ORDER
--------------------------------------------------------

  ALTER TABLE "USER2022"."TYPE_RECEIPT_ORDER" MODIFY ("ID_TYPE_RECEIPT_ORDER" NOT NULL ENABLE);
  ALTER TABLE "USER2022"."TYPE_RECEIPT_ORDER" ADD PRIMARY KEY ("ID_TYPE_RECEIPT_ORDER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
